---
- name: Configure nginx
  hosts: webservers
  become: yes

  tasks:

    - name: install nginx
      apt: name=nginx update_cache=yes
   
    - name: restart nginx
      service: name=nginx state=restarted  
